server:
  port: 8052

spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://localhost:8051
  cloud:
    gateway:
      mvc:
       routes:
       - id: order-service
         uri: lb://order-service
         predicates:
           - Path=/order/**
#         filters:
#           - name: RequestRateLimiter
#             args:
#              redis-rate-limiter.replenishRate: 10
#              redis-rate-limiter.burstCapacity: 10
#          - name: CircuitBreaker
#            args:
#              name: order-service
#              fallbackuri: forward:/orderServiceFallback


       - id: product-service
         uri: lb://product-service
         predicates:
           - Path=/product/**

#         filters:
#          - name: RequestRateLimiter
#             args:
#               redis-rate-limiter.replenishRate: 1
#               redis-rate-limiter.burstCapacity: 1
#        filters:
#          - name: CircuitBreaker
#            args:
#             name: product-service
#              fallbackuri: forward:/productServiceFallback


       - id: payment-service
         uri: lb://payment-service
         predicates:
           - Path=/payment/**
#         filters:
#           - name: RequestRateLimiter
#             args:
#               redis-rate-limiter.replenishRate: 1
#               redis-rate-limiter.burstCapacity: 1
#        filters:
#          - name: CircuitBreaker
#            args:
#              name: payment-service
#              fallbackuri: forward:/paymentServiceFallback

okta:
  oauth2:
    issuer: https://dev-94014640.okta.com/oauth2/default
    audience: api://default
    client-id: 0oah3gbrci2NZwN265d7
    client-secret: KbGniS2trQh_kX_0hwrfdwPI3-DmQeF3fw6WYPfsJzw2FWcUctCXsWMsakm99hYD
    scopes: openid, profile, email, offline_access
