package com.nvsoftware.ProductService.service;

import com.nvsoftware.ProductService.entity.ProductEntity;
import com.nvsoftware.ProductService.model.ProductRequest;
import com.nvsoftware.ProductService.repository.ProductRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service //implement a service
public class ProductServiceImpl implements ProductService {
    @Autowired
    private ProductRepository productRepository;

    @Override
    public long addProduct(ProductRequest productRequest) {
        ProductEntity productEntity = ProductEntity.builder() //Entity deal with DB
                .name(productRequest.getName())
                .price(productRequest.getPrice())
                .quantity(productRequest.getQuantity())
                .build();
        productRepository.save(productEntity); //Name, price and quantity , transfer from user
        return productEntity.getId(); // auto generated by DB, return to user
    }
}
